- name: cli-plugin-workspace
  referenceId: QWSFPS1U
  build:
    provider: dkcicd
    pipelines:
      - name: techdocs-v1
        parameters:
          entityReference: default/component/cli-plugin-workspace
          sourceDir: ./
        when:
          - event: push
            source: branch
            regex: master
            path:
              - "docs/**"
              - README.md
              - .vtex/deployment.yaml
      - name: node-ci-v2
        parameters:
          sonarProjectName: cli-plugin-workspace
          gitBaseBranchName: "master"
          nodeVersion: 20-bookworm
          nodeCommands:
            - test -- --passWithNoTests --coverage
        runtime:
          architecture: amd64
        when:
          - event: pull_request
            source: branch
          - event: push
            source: branch
            regex: master
